### ISSUE TITLE
private load balancer and private IP for the cluster

### ISSUE THREAD

**Issue by uasaigoli** [sethvargo/vault-on-gke#10]
**Question**
Existing script provided publicly accessible IP address. My organization does not want exposed vault IP to external world, instead want access the vault inside the firewall.

How can I easily add private IP to the cluster my minimally changing the script? By private static IP I should able to access the vault with same VPC (project) or other project by shared VPC?

I may need your guidance to make sure I am thinking this right. Do I need to do anything to make newly created IP is indeed internal IP ? vault.yml I have marked it as `internal`, is that it?

In [gcp.tf](https://github.com/sethvargo/vault-on-gke/blob/master/terraform/gcp.tf), I see following changes?

```
# Provision internal IP 
resource "google_compute_address" "vault-int" {
  name    = "vault-lb-int"
  region  = "${var.region}"
  project = "${google_project.vault.project_id}"

  depends_on = ["google_project_service.service"]
}

output "address-int" {
  value = "${google_compute_address.vault-int.address}"
}
```
In [k8s.tf](https://github.com/sethvargo/vault-on-gke/blob/master/terraform/k8s.tf)
```
data {
    load_balancer_address = "${google_compute_address.vault.address}"
    load_balancer_address_int = "${google_compute_address.vault-int.address}"
    gcs_bucket_name       = "${google_storage_bucket.vault.name}"
    kms_key_id            = "${google_kms_crypto_key.vault-init.id}"
  }

vars {
    load_balancer_ip_int  = "${google_compute_address.vault-int.address}"
    num_vault_servers = "${var.num_vault_servers}"
  }
```
in [tls.tf](https://github.com/sethvargo/vault-on-gke/blob/master/terraform/tls.tf)

```
ip_addresses = [
    "127.0.0.1",
    "${google_compute_address.vault.address}",
    "${google_compute_address.vault-int.address}",
  ]

```
In [vault.yml](https://github.com/sethvargo/vault-on-gke/blob/master/k8s/vault.yaml) - ADD new service??
```
apiVersion: v1
kind: Service
metadata:
  name: vault-int
 annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: vault
spec:
  type: LoadBalancer
  loadBalancerIP: ${load_balancer_ip_int}
  selector:
    app: vault
  ports:
  - name: vault-port
    port: 8200
    targetPort: 8200
    protocol: TCP
```

**Comment by sethvargo** [comment]
That looks right - is that not working for you?

**Comment by uasaigoli** [comment]
Thanks @sethvargo for reviewing my changes; I did not gave confidence in push the `apply` and I have one more thing to ask.

I see following section in vault.yml, do I need to make any changes to below section ? 

```
env:
        - name: POD_IP_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: LOAD_BALANCER_ADDR
          valueFrom:
            configMapKeyRef:
              name: vault
              key: load_balancer_address
        - name: GCS_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: vault
              key: gcs_bucket_name
        - name: VAULT_LOCAL_CONFIG
          value: |
            api_addr     = "https://$(LOAD_BALANCER_ADDR):8200"
            cluster_addr = "https://$(POD_IP_ADDR):8201"

            ui = true

            storage "gcs" {
              bucket     = "$(GCS_BUCKET_NAME)"
              ha_enabled = "true"
            }

            listener "tcp" {
              address       = "0.0.0.0:8200"
              tls_cert_file = "/etc/vault/tls/vault.crt"
              tls_key_file  = "/etc/vault/tls/vault.key"
            }
        readinessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true
            port: 8200
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
```

**Comment by sethvargo** [comment]
You shouldn't need to make any changes there. Vault is going to bind the to load balancer address, it will be an internal address instead of external, but that's okay

**Comment by uasaigoli** [comment]
I did `apply` my changes and good news is that no errors. 2 items from m change.

1. It created yet another EXTERNAL IP for me. looks like it did not care for the annotation `cloud.google.com/load-balancer-type: "Internal"`. looks like I need change service type from `LoadBalancer` to `NodePort`, and I will remove annotation. Does that make sense? 
2. It did not create forward rile for the new IP. where would I change that so that newly created IP forwards to the vault cluster?

**Comment by sethvargo** [comment]
1. I'm not sure why it would do that. It's on my list to expand this to support new VPC-space GKE and internal load balancers. Make sure your YAML is lined up correctly. In the snippet you provided, `annotations` is outdented too much

```yaml
apiVersion: v1
kind: Service
metadata:
  name: vault
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
```

2. The internal LB should be on the same subnet, so there shouldn't be a need for a forwarding rule.

**Comment by uasaigoli** [comment]
my annotation indentation looks ok to me.

[console service list looks like this](https://imgur.com/OobcM3F)
[VPC network and ext IP looks like this](https://imgur.com/dUWbJT3)

Am I reading this incorrectly may be?
on other note, is it easy to convert existing external load balancer to INTERNAL load balancer ?

```
apiVersion: v1
kind: Service
metadata:
  name: vault
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: vault
spec:
  type: LoadBalancer
  loadBalancerIP: ${load_balancer_ip}
  selector:
    app: vault
  ports:
  - name: vault-port
    port: 8200
    targetPort: 8200
    protocol: TCP
```
