### ISSUE TITLE
Permission iam.serviceAccountKeys.get is required to perform this operation on service account key

### ISSUE THREAD

**Issue by dalekurt** [sethvargo/vault-on-gke#33]
**Question**
Hey @sethvargo I am having a issue which results in the following:

```
Error: Error refreshing state: 3 error(s) occurred:

* kubernetes_config_map.vault: kubernetes_config_map.vault: Get http://localhost/api/v1/namespaces/default/configmaps/vault: dial tcp [::1]:80: connect: connection refused
* google_service_account_key.vault: 1 error(s) occurred:

* google_service_account_key.vault: google_service_account_key.vault: Error reading Service Account Key "projects/project-vault/serviceAccounts/vault-server@project-vault.iam.gserviceaccount.com/keys/xxxxbeed5d9eeec1658d7fdd319afa5b57e": googleapi: Error 403: Permission iam.serviceAccountKeys.get is required to perform this operation on service account key projects/project-vault/serviceAccounts/vault-server@project-vault.iam.gserviceaccount.com/keys/xxxxbeed5d9eeec1658d7fdd319afa5b57e., forbidden
* kubernetes_secret.vault-tls: 1 error(s) occurred:

* kubernetes_secret.vault-tls: kubernetes_secret.vault-tls: Get http://localhost/api/v1/namespaces/default/secrets/vault-tls: dial tcp [::1]:80: connect: connection refused
```

As been reported before [here](https://github.com/sethvargo/vault-on-gke/issues/4). I followed the instructions to remedy the problem, but to no avail.

I created a Service Account with `roles/owner` to test and update the `gcp.tf` to use the credential, however the result was:

```
...
Error: Error refreshing state: 3 error(s) occurred:

* google_service_account_key.vault: 1 error(s) occurred:

* google_service_account_key.vault: google_service_account_key.vault: Error reading Service Account Key "projects/project-vault/serviceAccounts/vault-server@project-vault.iam.gserviceaccount.com/keys/xxxxbeed5d9eeec1658d7fdd319afa5b57e": googleapi: Error 403: Permission iam.serviceAccountKeys.get is required to perform this operation on service account key projects/project-vault/serviceAccounts/vault-server@project-vault.iam.gserviceaccount.com/keys/xxxxbeed5d9eeec1658d7fdd319afa5b57e., forbidden
* kubernetes_secret.vault-tls: 1 error(s) occurred:

* kubernetes_secret.vault-tls: kubernetes_secret.vault-tls: Get http://localhost/api/v1/namespaces/default/secrets/vault-tls: dial tcp [::1]:80: connect: connection refused
* kubernetes_config_map.vault: kubernetes_config_map.vault: Get http://localhost/api/v1/namespaces/default/configmaps/vault: dial tcp [::1]:80: connect: connection refused
```

My user account with GCP is Project Owner `roles/owner` and I removed the configuration for gcloud and authenticated with both `gcloud auth login` and `gcloud auth application-default login` and I'm still getting the errors as stated above. Am I missing something?

**Comment by sethvargo** [comment]
Hi @dalekurt 

You shouldn't be using the vault-server service account to run Terraform. You should be using your local auth credentials for yourself (your user). 

Make sure you unset all `GOOGLE_*` environment variables and make sure you don't have a `terraform.tfvars` file with credentials filled in. 

I'm a little bit confused about what step(s) you took to get here. Can you walk me through it from the beginning please?

**Comment by dalekurt** [comment]
Hi @sethvargo, 

So I have a GCP project which exists, so I'm deploy terraform there. I commented the resource `google-project.vault` and the variables in the `variablles.tf` file which are used `org_id` and `billing_account`. Then updated all references to that resource from `google_project_.vault` to `var.project`. 

I created a `terraform.tfvars` with `project = "my-project-vault"`. Then executed the `gcloud auth application-default login`  which now just has one active account. 

`terraform init`
`terraform plan`
```
...
google_container_cluster.vault: Refreshing state... (ID: vault)
kubernetes_config_map.vault: Refreshing state... (ID: default/vault)
kubernetes_secret.vault-tls: Refreshing state... (ID: default/vault-tls)

Error: Error refreshing state: 3 error(s) occurred:

* kubernetes_config_map.vault: kubernetes_config_map.vault: Get http://localhost/api/v1/namespaces/default/configmaps/vault: dial tcp [::1]:80: connect: connection refused
* google_service_account_key.vault: 1 error(s) occurred:

* google_service_account_key.vault: google_service_account_key.vault: Error reading Service Account Key "projects/my-project-vault/serviceAccounts/vault-server@my-project-vault.iam.gserviceaccount.com/keys/7beef9edaced5d91afcc1658d7faa319afa5b57e": googleapi: Error 403: Permission iam.serviceAccountKeys.get is required to perform this operation on service account key projects/my-project-vault/serviceAccounts/vault-server@my-project-vault.iam.gserviceaccount.com/keys/7beef9edaced5d91afcc1658d7faa319afa5b57e., forbidden
* kubernetes_secret.vault-tls: 1 error(s) occurred:

* kubernetes_secret.vault-tls: kubernetes_secret.vault-tls: Get http://localhost/api/v1/namespaces/default/secrets/vault-tls: dial tcp [::1]:80: connect: connection refused
```

Does anything looks screwy with it? I have no environment variables with `GOOGLE_*` at the moment. 

I have posted a Gist [here](https://gist.github.com/dalekurt/3e4f1d9b1d45eb3a1622a60aa9d12cff)

**Comment by sethvargo** [comment]
The `Get ... http://localhost` calls are because it didn't download the kubernetes context. The `Error reading service account` error means that the credentials which you're using to execute Terraform don't have permission to get service accounts on that project.

- What's the output of `gcloud auth list`?
- What is the output of `gcloud iam service-accounts describe vault-server@my-project-vault.iam.gserviceaccount.com`?

**Comment by dalekurt** [comment]
```
gcloud auth list
        Credentialed Accounts
ACTIVE  ACCOUNT
*       dale.murray@sema4genomics.com

To set the active account, run:
    $ gcloud config set account `ACCOUNT`
```

```
gcloud iam service-accounts describe vault-server@my-project-vault.iam.gserviceaccount.com
ERROR: (gcloud.iam.service-accounts.describe) PERMISSION_DENIED: Permission iam.serviceAccounts.get is required to perform this operation on service account projects/-/serviceAccounts/vault-server@my-project-vault.iam.gserviceaccount.com
```

As well, there is not service account called vault-server@my-project-vault.iam.gserviceaccount.com in my service accounts for this project. Should that have been created manually or during the terraform plan/apply?

Also my account has the role `Owner`

**Comment by sethvargo** [comment]
These configurations aren't designed to be used in an existing project. In fact, it's actively discouraged to run Vault in an existing project. Instead we recommend running it in an isolated project.

The error message from gcloud is clear though: your currently logged in user does not have permission to get service accounts.

**Comment by dalekurt** [comment]
@sethvargo I agree with you, this project only intended to host vault, so to confirm it is isolated. 

-- Additional information, we request GCP projects from IT and populate it with the resources. So this project was created by IT and I'm deploying vault there. So the changes made just reflect the existing `project` held by the variable in the `terraform.tfvars` file. And the `gcp.tf` file was updated accordingly. 
 
I'm still grasping the hierarchy of GCP IAM roles, I made the assumption that `roles/owner` has the highest privilege and would be able to create the resources. Was I incorrect on that assumption.

**Comment by sethvargo** [comment]
_Where_ does your account have `roles/owner`? What is the output of 

```
$ gcloud projects get-iam-policy YOUR_PROJECT
```

**Comment by dalekurt** [comment]
I obscured the users and some details but this is it:

```
bindings:
- members:
  - serviceAccount:splunk@my-project-vault.iam.gserviceaccount.com
  role: roles/appengine.appViewer
- members:
  - serviceAccount:splunk@my-project-vault.iam.gserviceaccount.com
  role: roles/cloudfunctions.viewer
- members:
  - serviceAccount:service-123456789012@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:splunk@my-project-vault.iam.gserviceaccount.com
  role: roles/compute.viewer
- members:
  - serviceAccount:service-123456789012@container-engine-robot.iam.gserviceaccount.com
  role: roles/container.serviceAgent
- members:
  - serviceAccount:123456789012-compute@developer.gserviceaccount.com
  - serviceAccount:123456789012@cloudservices.gserviceaccount.com
  - serviceAccount:service-123456789012@containerregistry.iam.gserviceaccount.com
  - serviceAccount:terraform@my-project-vault.iam.gserviceaccount.com
  - user:dale.murray@sema4genomics.com
  role: roles/editor
- members:
  - serviceAccount:splunk@my-project-vault.iam.gserviceaccount.com
  role: roles/logging.privateLogViewer
- members:
  - serviceAccount:splunk@my-project-vault.iam.gserviceaccount.com
  role: roles/monitoring.viewer
- members:
  - user:dale.murray@sema4genomics.com
  - user:john1.doe@sema4genomics.com
  - user:john2.doe@sema4genomics.com
  - user:john3.doe@sema4genomics.com
  role: roles/owner
- members:
  - serviceAccount:splunk@my-project-vault.iam.gserviceaccount.com
  role: roles/pubsub.viewer
- members:
  - serviceAccount:splunk@my-project-vault.iam.gserviceaccount.com
  role: roles/servicemanagement.quotaViewer
- members:
  - serviceAccount:splunk@my-project-vault.iam.gserviceaccount.com
  role: roles/serviceusage.serviceUsageViewer
- members:
  - serviceAccount:docker-build-sa@my-core-dev.iam.gserviceaccount.com
  role: roles/storage.admin
- members:
  - serviceAccount:splunk@my-project-vault.iam.gserviceaccount.com
  role: roles/storage.objectViewer
- members:
  - serviceAccount:splunk@my-project-vault.iam.gserviceaccount.com
  - user:john4.doe@sema4genomics.com
  role: roles/viewer
etag: AwWACsxLlwA=
version: 1
```
