### ISSUE TITLE
Sealing vault pod (via UI) only seals a single pod

### ISSUE THREAD

**Issue by evanhfox** [sethvargo/vault-on-gke#36]
**Question**
I'm running into an interesting issue. When sealing the vault via the UI, only a single pod seals -- the two remaining vault pods (running vault and init containers) run and remain unsealed.  Is this a limitation of running vault on K8S? If not, it's likely I have an issue between pods. Any thoughts?

**Considerations**
1. Running vault pro instead of vault

2. Using an internal type LB instead of public:

I'm running an internal type load balancer, which is different than your service YAML.

```
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: vault
spec:
  type: LoadBalancer
  loadBalancerIP: 10.xxx.yyy.zzz
  selector:
    app: vault
  ports:
  - name: vault-port
    port: 443
    targetPort: 8200
    protocol: TCP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  labels:
    app: vault
spec:
  serviceName: vault
  replicas: 3
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 60
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: ["vault"]
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
      - name: vault-init
        image: "sethvargo/vault-init:1.0.0"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
        env:
        - name: GCS_BUCKET_NAME
          value: "xxxxxx-vault-bucket"
        - name: KMS_KEY_ID
          value: "projects/xxxxxx/locations/northamerica-northeast1/keyRings/xxxxxxx/cryptoKeys/xxxxx-vault-key"
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200"
        - name: VAULT_SECRET_SHARES
          value: "1"
        - name: VAULT_SECRET_THRESHOLD
          value: "1"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/credentials/credentials.json
        volumeMounts:
        - mountPath: /secrets/credentials
          name: service-account-credentials
      - name: vault
        image: "gcr.io/xxx-yyy-zzz/vault-enterpise:0.11.5"
        imagePullPolicy: Always
        args: ["server"]
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
        ports:
        - containerPort: 8200
          name: vault-port
          protocol: TCP
        - containerPort: 8201
          name: cluster-port
          protocol: TCP
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: vault-tls
          mountPath: /etc/vault/tls
        - mountPath: /secrets/credentials
          name: service-account-credentials
        env:
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200"
        - name: POD_IP_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/credentials/credentials.json
        - name: VAULT_LOCAL_CONFIG
          value: |
            api_addr     = "https://10.xxx.yyy.zzz"
            cluster_addr = "https://$(POD_IP_ADDR):8201"
            log_level = "warn"
            ui = true
            seal "gcpckms" {
              project    = "xxxx"
              region     = "northamerica-northeast1"
              key_ring   = "xxx-keyring"
              crypto_key = "xxx-vault-key"
            }
            storage "gcs" {
              bucket     = "xxxx-vault-bucket"
              ha_enabled = "true"
            }
            listener "tcp" {
              address     = "127.0.0.1:8200"
              tls_disable = "true"
            }
            listener "tcp" {
              address       = "$(POD_IP_ADDR):8200"
              tls_cert_file = "/etc/vault/tls/vault.pem"
              tls_key_file  = "/etc/vault/tls/vault.key"
              tls_disable_client_certs = true
            }
        readinessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true
            port: 8200
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: vault-tls
        secret:
          secretName: vault-tls
      - name: service-account-credentials
        secret:
          defaultMode: 420
          secretName: service-account-credentials
```
