### ISSUE TITLE
variable expansion in yaml heredoc

### ISSUE THREAD

**Issue by tammersaleh** [sethvargo/vault-on-gke#5]
Just double checking that this configuration is still working for you, as I seem to be hitting a strange bug.  It looks to me as though variable expansion isn't working [in the yaml heredoc](https://github.com/sethvargo/vault-on-gke/blob/master/k8s/vault.yaml#L103), though it does work elsewhere.  Here's my `env` output when exec'd from the running container in the statefulset:

``` bash
$ kubectl exec vault-0 -it -- env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=vault-0
TERM=xterm
VAULT_CLUSTER_ADDR=https://10.28.0.18:8201
GOOGLE_APPLICATION_CREDENTIALS=/etc/vault/secrets/service-account.json
VAULT_LOCAL_CONFIG=api_addr     = "https://$(LOAD_BALANCER_ADDR):8200"
cluster_addr = "https://10.28.0.18:8201"
ui = true
storage "gcs" {
  bucket     = "$(GCS_BUCKET_NAME)"
  ha_enabled = "true"
}
listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_cert_file = "/etc/vault/secrets/vault.crt"
  tls_key_file  = "/etc/vault/secrets/vault.key"
}

GCS_BUCKET_NAME=vault-redacted-vault-storage
POD_IP=10.28.0.18
VAULT_API_ADDR=https://vault:8201
```

Notice that `GCS_BUCKET_NAME` and `POD_IP` are set correctly, but `VAULT_LOCAL_CONFIG` has the non-expanded values.   Anyways, just wanted to see if you're seeing similar behavior before I create a ticket for this in the kubernetes repo.

...and here's my `env:` stanza from the stateful set:

``` yaml
env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "VAULT_API_ADDR"
              value: "https://vault:8201"
            - name: "VAULT_CLUSTER_ADDR"
              value: "https://$(POD_IP):8201"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/vault/secrets/service-account.json"
            - name: VAULT_LOCAL_CONFIG
              value: |
                api_addr     = "https://$(LOAD_BALANCER_ADDR):8200"
                cluster_addr = "https://$(POD_IP):8201"
                ui = true
                storage "gcs" {
                  bucket     = "$(GCS_BUCKET_NAME)"
                  ha_enabled = "true"
                }
                listener "tcp" {
                  address       = "0.0.0.0:8200"
                  tls_cert_file = "/etc/vault/secrets/vault.crt"
                  tls_key_file  = "/etc/vault/secrets/vault.key"
                }
            - name: GCS_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: vault
                  key: gcs_bucket_name
```
