### ISSUE TITLE
Application authentication using Spring Cloud Vault

### ISSUE THREAD

**Issue by uasaigoli** [sethvargo/vault-on-gke#9]
**What did you expect to happen?**
I wanted to use my spring based app to access the vault secret using spring cloud vault. I have setup approle based on https://www.vaultproject.io/docs/auth/approle.html and and my spring brootstrap.yaml has following. I was expecting authenticate.

```
spring.cloud.vault:
      uri: https://<IP>:8200
      authentication: APPROLE
      app-role:
        role-id: 5ff1c241-.....
        secret-id: de6580de-....
        role: app-role
        app-role-path: approle
```

**What actually happened?**
I/O error on POST request for "https://<IP>:8200/v1/auth/approle/login": sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; 

**Additional context**
Do I need to pass TLS cert path to "tls/ca.pem" somewhere in spring config (bootstrap.yml), I do not see any option to pass cert ? Isn't that double auth 1. approle and 2. SSL ?
